let setNumber = Number(prompt('enter the number', 0))
let setNumber2 = Number(prompt('enter the second number', 0))
let sum = (setNumber+setNumber2)
let mins = (setNumber-setNumber2)
let mult = (setNumber*setNumber2)
let divi = (setNumber/setNumber2)
alert("sum " + sum)
alert("minus " + mins)
alert("multiplicate " + mult)
alert("division " + divi)
