let setDigit = Number(prompt('enter digit', 0))
let setDigit2 = Number(prompt('enter second digit', 0))
let setDigit3 = Number(prompt('enter third digit', 0))
let prod = (setDigit+setDigit2+setDigit3)
alert("Среднее арифметическое =" + prod/3)