let enterNumber = Number(prompt('enter five-digit number', 0))
let dig = (enterNumber % 10)
let enterNumber1 = (enterNumber / 10)
enterNumber1 = parseInt(enterNumber1, 10)
let dig2 = (enterNumber1 % 10)
let enterNumber2 = (enterNumber1 / 10)
enterNumber2 = parseInt(enterNumber2, 10)
let dig3 = (enterNumber2 % 10)
let enterNumber3 = (enterNumber2 / 10)
enterNumber3 = parseInt(enterNumber3, 10)
let dig4 = (enterNumber3 % 10)
let enterNumber4 = (enterNumber3 / 10)
enterNumber4 = parseInt(enterNumber4, 10)
let dig5 = (enterNumber4 % 10)
alert(dig5+" "+dig4+" "+dig3+" "+dig2+" "+dig)
