let enterNumber = Number(prompt('enter five-digit number', 0))
let dig = (enterNumber % 10)
let enterNumber1 = (enterNumber / 10)
let dig2 = (enterNumber1 % 10)
let enterNumber2 = (enterNumber1 / 10)
let dig3 = (enterNumber2 % 10)
let enterNumber3 = (enterNumber2 / 10)
let dig4 = (enterNumber3 % 10)
let enterNumber4 = (enterNumber3 / 10)
let dig5 = (enterNumber3 % 10)
alert(dig+dig2+dig3+dig4+dig5)
